# .air.toml

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
cmd = "go run . serve"
bin = "tmp\\main.exe"
full_bin = ""
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_regex = ["_test.go"]
include_ext = ["go", "tpl", "tmpl", "html"]
kill_delay = "0s"
log = "build-errors.log"
rerun_delay = 500
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = true

[misc]
clean_on_exit = false

[proxy]
enabled = false

[screen]
clear_on_rebuild = true
keep_scroll = true
